### ISSUE TITLE
Remaining tasks for milestone 3 submission

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109_R#1]
Per the instructions in milestone3.md we will submit our milestone 3 and 34 on this project repository.

These are the remaining tasks for milestone 3:

1. Fork this repo and clone the forked repo (All)

2. Code in R and save of screenshots of working code and plots in img folder of this repo (All)

3. Save R files in src folder (All)

4. Consolidate screenshots of R code and plots into a single screenshot to be saved in img folder (Rob). When done, copy to your ubc.ca milestone 3 repo.

5. Update proposal to reflect new app functionality and appearance and save in doc folder of this repo (George)

6. Update dashboard sketch and save to img and folder and README in this repo (Rob)

7. Copy all required files from Python project repo to this repo (Rob to do):

- contributing
- license (done)
- README (copy of milestone 2 version and create new version for comparison)
- proposal
- code of conduct
- work contract (to your ubc.ca repo)

8. Review reflections.md and save in Python project repo but NOT this repo (Rob, George)

**Comment by RobBlumberg** [comment]
Thanks for summarizing the remaining tasks George. I have just copied the relevant files over from the python project repo and submitted a PR. 

As these tasks are completed, we should let everyone know in this thread.

**Comment by RobBlumberg** [comment]
closing as most have been addressed
