### ISSUE TITLE
[M3: R]

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI_532_GROUP_109_R#13]
Hello everyone,

fantastic update of your proposal, great progress and also great teamwork!

Here are some thoughts for an update or additions (you are welcome to implement this, these are not required for implementation, but for a reflection and discussion):
* You are doing a great job connecting you bar-plot of titanic cabin levels to the map of titanic. Think about ways and consider linking your third graph, displaying the class level of the passengers, better with the first two graphs. It is not clear yet, where first, second or third class passenger would be located on decks.
* consider shortening and sorting your commit messages using [DOC]= for documentation updates, [ENH] = for added functionality or interactivity, or [BUG] = for bug fixes

I am curious about the final app!

**Comment by gptzjs** [comment]
Hi Stephanie, thanks for your valuable feedback Stefanie which we have responded to in our reflections submission for this week. 

Sadly, heroku cannot seem to find the audio file so there will be no musical accompaniment to the dashboard to go along with the nice header image, but if you have any experience with this, please do let us know!
