### ISSUE TITLE
Tasks for next few days

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109_R#15]
Just thought I'd summarize the remaining tasks. In terms of the technical details and visualizations, we pretty much got everything done in lab today, so I dont think theres much left other than:

- Clean up app in terms of descriptions, plot annotations / possible formatting and maybe some layout stuff
- Add the legend for survived vs died in cabin plot
- Make sure reflections are completely up to date 
- Launch on heroku

**Comment by gptzjs** [comment]
Thanks Rob. 

I will add the legend for survived vs died in the cabin plot today and then review the cleanup points and review reflections. 

Let's aim to have everything done by tomorrow morning

**Comment by RobBlumberg** [comment]
I agree, I will launch the app on Heroku tonight once we've finished with the clean up

**Comment by trevorkwan** [comment]
thanks rob and george. I have drafted a reflection summarizing all our changes from previous milestones, and addressing all of the current milestone 4 TA feedback. I have left a bit of room if anyone wants to add anything about new changes.

**Comment by RobBlumberg** [comment]
Added the description and image of the ship just now. I think all that is left to do is to add the legend, which Geroge said he'd do, and maybe just add the sources we add last time. Then I'll launch it on heroku

**Comment by RobBlumberg** [comment]
All tasks now complete, so closing this issue
