### ISSUE TITLE
TA feedback on milestone 2 > Action required

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109_R#3]
**1. I see that you are always commiting and using pull requests, but try to add an extended description of the commits that you find a little vague.** 

_> Let's make a rule of not merging a PR or replying or closing an issue without a proper and relevant comment_

**2. You also use issues for communication and task assignment, but I see that team members tend not to comment on issues.**

_See above_

**3. Regarding the app, I like how you use a mix of bar charts, the ship plots for visualizations. I have some suggestions for the app that I will be listing below.**

_See below_

**4. It is always required for an online visualization tool to have a description of the app at the beginning (user's guide).**

_Will clarify whether he wants this on the dashboard itself and/or a separate doc on the repo. Either way, I will write it up a draft for you guys to review._

**5. I tried the app on Firefox first and it didn't work (I couldn't see the charts), but it worked perfectly on Chrome. Is there something you can do?**

_Found the link below which suggests it could be due to different installed versions of the following dependencies:_ 

https://community.plot.ly/t/dash-table-and-graph-does-not-load-in-browser/23139/4

_dash-renderer
dash-core-components
dash-html-components_

_But if this is the case, not every user is going to have these installed (at all regardless of version) so how can an app be widely used?_

**6. You should include or cite the data source.**
_Easily done. Suggest we put these at the bottom left of the app a few whitespace rows below the bar chart._

**7. You have used some interactive features which I find very helpful for users.**

_Glad he likes it. Wait till we get the music._

**8. Finally, I like your reflection you did everything that was required in this task**

_All good_

**Comment by RobBlumberg** [comment]
I will try to address point 5. And definitely agree we should be more descriptive when we merge PRs and comment more often on issues

**Comment by gptzjs** [comment]
What is the raw data source? We also used Encyclopedia Titanica right? For the image. the source is fxguide.com. We could list the sources like this with the references as links to the source:

Data sources: [Encyclopedia Titanica](https://www.encyclopedia-titanica.org/)
Image source: [fxguide.com](https://www.fxguide.com/fxfeatured/titanic-stories/)

**Comment by RobBlumberg** [comment]
yes I think that would be fine. The titanic data itself came from a previous lab, and is also available through kaggle, though I'm not sure they are the primary source. So not sure on the citation for that one

**Comment by RobBlumberg** [comment]
Also, this discussion might be better to have in the python repo?
