### ISSUE TITLE
Plot images

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_532_GROUP_109_R#5]
I have just submitted a PR containing the R code used to create the titanic cabin location plot. The R code is an Rscript file that I have placed in the src directory, (but feel free to use any R file type  when you make your plots - Rmd, jupyter notebook, etc.). I have included an image of the code / plot in the img directory to show our progress. You can refer to that image to have an idea of what to produce, and once you've dropped your images in the img directory, I'll create one big image that we can drop into the README (right now, only my plot image is there as a placeholder).

**Comment by gptzjs** [comment]
Perfect. Will get the same done today for the deck plot and Trevor can do the same for the class plot.

**Comment by trevorkwan** [comment]
i have created the plot named "class_plot_in_r". there is an rscript containing that code under "src/data", and an image containing the finished plot under "img"
i will send a PR now for those changes

**Comment by RobBlumberg** [comment]
Sounds good. Once I merge that PR I will close this issue.

**Comment by RobBlumberg** [comment]
done, so closing
