### ISSUE TITLE
Some ideas to enhance the plots

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109_R#6]
Thinking of putting the average ticket price in the bars for each class to show the disparity in price of tickets by class. This shows that Class 1 is the "highest" class and drives home the EDA issue that passenger safety should not discriminate on ticket price (i.e.. a proxy for wealth and privilege). People are drawn to pictures as we have seen from the reaction to our image, and their eyes also light up for money, so I think it would quickly bring the research question into focus 
since we can easily see that there is a significant difference in survival rates by class which we could easily test to show statistical significance (e.g. MLR with three categorical variables).

Plot title could be changed to "Survival Rate and Average Ticket Price by Class" and then we just put in the center of each of the three bars the ticket price in white font (e.g. $50) . Based on the information I was able to find, I am quite confident putting in the prices will be quite provocative and eye-opening in a useful way.

We should just put the actual price in 1912 dollars and then I can write up some original text to translate this into 2019 dollars.

For the deck plot, we could also consider putting in a note to show that A is at a higher elevation than G. Again as with class, this can be inferred but is not clearly stated. Removes any ambiguity. You don't want users to be uncertain about the key facts of your visualization. There was a lot of that in the other two groups I gave feedback to yesterday.

**Comment by RobBlumberg** [comment]
I agree with these changes, but am wondering if you're suggesting changing these for the python app, or eventually implementing them in the R app? I think ideally for both, yes, but we also need to be realistic about how many changes we can implement in the next 24 hours or so

**Comment by gptzjs** [comment]
Good point. Let's focus on these changes for R first given time constraints and then make the changes for Python if time permits

**Comment by RobBlumberg** [comment]
Sounds good
