### ISSUE TITLE
added reflection and class plot

### ISSUE THREAD

**Issue by trevorkwan** [UBC-MDS/DSCI_532_GROUP_109_R#8]
i have just sent a PR to the new R repo containing 4 changes:
1 . added reflection in word doc form in "docs" folder
2. added reflection in .md form in "docs" folder
3. added class plot image in "img" folder
4. added class plot code script in "src" folder

**Comment by RobBlumberg** [comment]
I just read the reflections, and we actually didn't end up doing a few things, like changing the color of the dots in the ship to blue, we left them white in the end. Also, I think we should mention in reflections how we refactored our code (did wrangling externally and imported data to functions. And that this had a significant impact on the speed at which our interactive plot updates, enhancing user experience). And also we can mention the music

**Comment by gptzjs** [comment]
Thanks I saw that too. Updating it now with a few other edits.
